subject_train <- read.table("./UCI HAR Dataset/train/subject_train.txt", col.names="subject")
label_train <- read.table("./UCI HAR Dataset/train/Y_train.txt", col.names="activity_id")
features <- read.table("./UCI HAR Dataset/features.txt")
data_train <- read.table("./UCI HAR Dataset/train/X_train.txt", col.names=features[,2])
df_train <- cbind(subject_train, label_train, data_train)
rm(data_train, label_train, subject_train)
subject_test <- read.table("./UCI HAR Dataset/test/subject_test.txt", col.names="subject")
label_test <- read.table("./UCI HAR Dataset/test/Y_test.txt", col.names="activity_id")
data_test <- read.table("./UCI HAR Dataset/test/X_test.txt", col.names=features[,2])
df_test <- cbind(subject_test, label_test, data_test)
rm(data_test, label_test, subject_test, features)
merged_df <- rbind(df_train, df_test)
rm(df_train, df_test)
library(dplyr)
merged_df <- tbl_df(merged_df)
selected_df <- select(merged_df, subject, activity_id, contains("mean"), contains("std"), -contains("meanFreq"))
activity_label <- read.table("./UCI HAR Dataset/activity_labels.txt", col.names=c("activity_id","activity_label"))
selected_df2 <- merge(selected_df, activity_label, by.x="activity_id", by.y="activity_id")
tidy_data <- select(selected_df2, subject, activity_label, 3:75)
data_melt <- melt(tidy_data, id.vars=c("subject", "activity_label"))
tidy_data2 <- dcast(data_melt, subject+activity_label ~ variable, mean)
rm(merged_df, activity_label, selected_df, selected_df2, data_melt)
tidy_data2
